name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Debug file paths
        run: |
          echo "Current directory:"
          pwd
          echo "Listing root directory:"
          ls -al
          echo "Listing moviewsd directory:"
          ls -al moviewsd

      - name: Install dependencies
        working-directory: moviewsd
        run: npm install

      - name: Build project
        working-directory: moviewsd
        run: npm run build

      - name: Commit and Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # dist 폴더의 경로가 맞는지 확인
          publish_dir: moviewsd/dist
          # 브랜치 이름 설정 (gh-pages)
          publish_branch: gh-pages
          commit_message: "Deploy to GitHub Pages"
