name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: moviewsd
        run: npm install

      - name: Build project
        working-directory: moviewsd
        run: npm run build

      - name: Deploy to GitHub Pages from main
        run: |
          git config --global user.name "woojung1234"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git worktree add dist gh-pages
          cp -R moviewsd/dist/* dist/

          cd dist
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
