name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: moviewsd
        run: npm install

      - name: Build project
        working-directory: moviewsd
        run: npm run build

      - name: Commit and Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # dist 폴더 경로
          publish_dir: moviewsd/dist
          # 배포할 브랜치 (gh-pages)
          publish_branch: main
          # 커밋 메시지 설정
          commit_message: "Deploy to GitHub Pages"
